
tshirts = [
  {
    name:"Half sleeve T-shirt",
    price:"250",
    mrp:"600",
    images:[
      "./assets/images/2.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
    ]
  },
  {
    name:"Half sleeve T-shirt",
    price:"300",
    mrp:"600",
    images:[
      "./assets/images/3.jpg",
       "../../assets/images/T-Shirts/halfSleeveGrey/2.jpg",
       "../../assets/images/T-Shirts/halfSleeveGrey/3.jpg",
       "../../assets/images/T-Shirts/halfSleeveGrey/4.jpg",
       "../../assets/images/T-Shirts/halfSleeveGrey/5.jpg"
    ]
  },
  {
    name:"Full sleeve T-shirt",
    price:"300",
    mrp:"600",
    images:[
      "./assets/images/4.jpg",
      "../../assets/images/T-Shirts/halfSleeveBlue/2.jpg",
       "../../assets/images/T-Shirts/halfSleeveBlue/3.jpg",
       "../../assets/images/T-Shirts/halfSleeveBlue/4.jpg",
       "../../assets/images/T-Shirts/halfSleeveBlue/5.jpg"
    ]
  },
  {
    name:"Tank Tops",
    price:"250",
    mrp:"600",
    images:[
      "./assets/images/5.jpg",
       "./assets/images/black.jpg",
       "./assets/images/black.jpg",
       "./assets/images/black.jpg",
       "./assets/images/black.jpg",
    ]
  },
  {
    name:"Track Pants",
    price:"250",
    mrp:"600",
    images:[
      "./assets/images/6.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
    ]
  },
  {
    name:"Polo T-Shirts",
    price:"300",
    mrp:"600",
    images:[
      "./assets/images/7.jpg",
      "../../assets/images/T-Shirts/halfSleeveGrey/2.jpg",
       "../../assets/images/T-Shirts/halfSleeveGrey/3.jpg",
       "../../assets/images/T-Shirts/halfSleeveGrey/4.jpg",
       "../../assets/images/T-Shirts/halfSleeveGrey/5.jpg"
    ]
  },
  {
    name:"Track Pants",
    price:"300",
    mrp:"600",
    images:[
      "./assets/images/8.jpg",
       "../../assets/images/T-Shirts/halfSleeveBlue/2.jpg",
       "../../assets/images/T-Shirts/halfSleeveBlue/3.jpg",
       "../../assets/images/T-Shirts/halfSleeveBlue/4.jpg",
       "../../assets/images/T-Shirts/halfSleeveBlue/5.jpg"
    ]
  },
  {
    name:"Coords",
    price:"250",
    mrp:"600",
    images:[
      "./assets/images/9.jpg",
      "./assets/images/black.jpg",
       "./assets/images/black.jpg",
       "./assets/images/black.jpg",
       "./assets/images/black.jpg",
       "./assets/images/black.jpg",
    ]
  },
  {
    name:"Trousers",
    price:"250",
    mrp:"600",
    images:[
      "./assets/images/10.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
      "./assets/images/blue.jpg",
    ]
  },  
]   
